### ISSUE TITLE
Conditional panels aren't laid out correctly v0.2.3

### ISSUE THREAD

**Issue by matt-aitken** [hipstersmoothie/react-window-splitter#19]
This was working correctly in the previous version. In my app as well as in the docs the conditional panel is appearing below the other panel(s) instead of alongside (when in horizontal orientation).

You can see this bug on the docs page: https://react-window-splitter-six.vercel.app/docs/examples/conditional

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v0.2.4`](https://github.com/hipstersmoothie/react-window-splitter/releases/tag/v0.2.4) :rocket:
